name = "Sandboxes"
uuid = "c7e15cf0-901b-416d-9580-018ad2582128"
authors = ["Colin Caine <cmcaine@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
